version: '3'
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    expose:
     - "9100"
  nginx:
   image: nginx:latest
   restart: unless-stopped
   ports:
    - '80:80'
   volumes:
    - '/root/exporters/nginx.conf:/etc/nginx/nginx.conf:rw'
